app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/movies
      username: postgres
      password: postgres
      pool-size: 30